sudo: false
language: java
jdk:
- openjdk8
install: "./gradlew --version"
script: ./gradlew --no-daemon -DGRADLE_OPTS="-Xms128m" --stacktrace build -i
after_success:
- git status
- echo $REPOSITORY_USERNAME
- echo $TRAVIS_PULL_REQUEST
- echo $TRAVIS_BRANCH
- if [ master == $TRAVIS_BRANCH -a $TRAVIS_PULL_REQUEST == false -a  ${REPOSITORY_USERNAME:=X}
  != X ]; then ./gradlew -DGRADLE_OPTS="-Xms128m" release -i; fi
cache:
  directories:
  - "$HOME/.gradle"
env:
  global:
    secure: eS66pbnE2qPTDOB+wX8KvWD5NjwaWDelGWpE/FIZKnCXr0EK/CUI6DyERt6qLOHMRXySyUnYMPMVV3U2v7dn4OD5nlaVbwD9slld/VT5sJ6KtlQlVcTh34OxXf3FADggaZg9kPfXyuSHIOV+vkaTkm0PZgvgCn038jm47cckJYpiO82GsOEqcc08/nzKJ0TccnH4I2Zem3RYoKgyg5yOwx8gDibyt5pmv/OzKvEAg7zvA4hAa47Ql3AZ2e7K8L3NOe75EOj4Vt6FCguzNDtvX7QsHtrln0strAcJFcVzzhDaDswBykX25Zj/3Hr4OWhBXGcWW8yOYfLL7PQyEwh/wSeuiNOAv9tGmItX517eHFuNvW2PUbYYrsAWgVYsMttmTC77vRqI/TFj1kQ+jPvtnukhAqvMh+JynBvZo3E7FROncv56QHlzMdoB87EXQL9XxHLkOVKXNwEveCNYszcruTXYC+p22pTUsZ5SEw7uek1JYdSEea+t4OfDkyrPF6E80ZheWDoPXTJFGqTKgaYz21pcrGjcuMqEqaqhu5J3Te2Sm673ueS7og9KU7Zi/z3hwsumkNTuVbY683Bq0elCpq+0+cNSoKAinnX9xLg2KsVt4g3YG67X2L7HQPDxwKcL0ySCH8ZYD056JsmQHcsmOgqjZ5C/7OteNzoujX96z3E=
